### PR TITLE
TList<T> and TDictionary<T> should not have any constraint, while TOb…

### PR DESCRIPTION
**Pull request by obones**
…jectList<T> and TObjectDictionary<T> are the ones to be constrained on class

### CODE REVIEW

**Comment by dwarfland** [comment]
> TList<T> = public class(TEnumerable<T>){$IF TOFFEE}where T is class;{$ENDIF}

I'm afraid that is a limitation of the Cocoa platform; we can not support generics for non-classes here. This should not affect your use of Delphi RTL on .NET though?

**Comment by obones** [comment]
Well, I've had errors popup in my .Net project because my class derived from `TList<T>` does not constrain on class. And `TObjectList` is not declared either.
But maybe I had something wrong here and that the IFDEF should be placed somewhere else

**Comment by dwarfland** [comment]
I'll have a look. the Dictionary changes look like the might be ok, but the change on list woudkl *only* affect TOFFEE (you're just removing an {$IF TOFFEE}-limited constrained; so that one's (a) bad and (b) irrelevant for you for sure.

**Comment by obones** [comment]
Yes, and maybe the `TObjectList` declaration should have no IFDEF at all actually

**Pull request closed without merging**
