### PR TITLE
Under Echoes, make TClass an alias for System.Type 

### PR DESCRIPTION
**Pull request by obones**
This allows implementing quite a few methods on Object_Delphi

### CODE REVIEW

**Comment by dwarfland** [comment]
Can we make it an alias for RemObjects.Elements.RTL.Reflection.Type for all platforms, instead?

**Comment by obones** [comment]
Did not know about that one so I tried, and... ok, it works much better for most cases, except Cooper who is giving me a hard time for `InheritsFrom` because `IsSubclassOf` is not available
Any suggestions?

**Comment by dwarfland** [comment]
I'll have a look later today, for juts ifdef the ones that don't work out for Cooper.

**Comment by dwarfland** [comment]
I already fixed the alias in master. But i didn't merge your implementations yet (as us sine they'll be slightly different now)

**Pull request merged**
