### PR TITLE
Implement the enumerator with a real class

### PR DESCRIPTION
**Pull request by obones**
This appears to be much better accepted by all targets.

### CODE REVIEW

**Comment by dwarfland** [comment]
isn't this one already solved in latest?

**Comment by obones** [comment]
Indeed, with a more recent compiler, this is no longer required

**Comment by obones** [comment]
Indeed, with a more recent compiler, this is no longer required

**Comment by obones** [comment]
Indeed, with a more recent compiler, this is no longer required

**Pull request closed without merging**
